[2022-06-21 12:22:36,839] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.json_to_df manual__2022-06-21T12:22:30.735842+00:00 [queued]>
[2022-06-21 12:22:36,851] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.json_to_df manual__2022-06-21T12:22:30.735842+00:00 [queued]>
[2022-06-21 12:22:36,852] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 12:22:36,853] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-06-21 12:22:36,853] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 12:22:36,868] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): json_to_df> on 2022-06-21 12:22:30.735842+00:00
[2022-06-21 12:22:36,873] {standard_task_runner.py:52} INFO - Started process 144 to run task
[2022-06-21 12:22:36,879] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'todoist_load_to_pg', 'json_to_df', 'manual__2022-06-21T12:22:30.735842+00:00', '--job-id', '512', '--raw', '--subdir', 'DAGS_FOLDER/todoist_load_to_pg.py', '--cfg-path', '/tmp/tmp2d_z8n22', '--error-file', '/tmp/tmpiz9odd9h']
[2022-06-21 12:22:36,881] {standard_task_runner.py:77} INFO - Job 512: Subtask json_to_df
[2022-06-21 12:22:36,945] {logging_mixin.py:109} INFO - Running <TaskInstance: todoist_load_to_pg.json_to_df manual__2022-06-21T12:22:30.735842+00:00 [running]> on host bd658c040114
[2022-06-21 12:22:37,005] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=emil
AIRFLOW_CTX_DAG_ID=todoist_load_to_pg
AIRFLOW_CTX_TASK_ID=json_to_df
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T12:22:30.735842+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T12:22:30.735842+00:00
[2022-06-21 12:22:37,029] {todoist_load_to_pg.py:54} INFO -            id  color                           name  comment_count  shared  \
0  2266101084     48                          Inbox              0   False   
1  2266102370     31                         Работа              0   False   
2  2281199547     46                        Проекты              0   False   
3  2276172551     41                        Финансы              0   False   
4  2275765087     33  Организационно-бытовые задачи              0   False   
5  2275777802     36             Красота и здоровье              0   False   
6  2275765259     37           Личная эффективность              0   False   
7  2286290517     34                           Soft              0   False   
8  2276173208     30                          Семья              0   False   
9  2281200101     35                         Друзья              0   False   

   favorite  sync_id inbox_project  \
0     False        0          True   
1     False        0           NaN   
2     False        0           NaN   
3     False        0           NaN   
4     False        0           NaN   
5     False        0           NaN   
6     False        0           NaN   
7     False        0           NaN   
8     False        0           NaN   
9     False        0           NaN   

                                             url  order  \
0  https://todoist.com/showProject?id=2266101084    NaN   
1  https://todoist.com/showProject?id=2266102370    1.0   
2  https://todoist.com/showProject?id=2281199547    2.0   
3  https://todoist.com/showProject?id=2276172551    3.0   
4  https://todoist.com/showProject?id=2275765087    4.0   
5  https://todoist.com/showProject?id=2275777802    5.0   
6  https://todoist.com/showProject?id=2275765259    6.0   
7  https://todoist.com/showProject?id=2286290517    7.0   
8  https://todoist.com/showProject?id=2276173208    8.0   
9  https://todoist.com/showProject?id=2281200101    9.0   

                     dag_run  
0 2022-06-21 12:22:37.019485  
1 2022-06-21 12:22:37.019485  
2 2022-06-21 12:22:37.019485  
3 2022-06-21 12:22:37.019485  
4 2022-06-21 12:22:37.019485  
5 2022-06-21 12:22:37.019485  
6 2022-06-21 12:22:37.019485  
7 2022-06-21 12:22:37.019485  
8 2022-06-21 12:22:37.019485  
9 2022-06-21 12:22:37.019485  
[2022-06-21 12:22:37,030] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/todoist_load_to_pg.py", line 55, in json_to_df
    postgres_hook = PostgresHook(self.pg_con)
NameError: name 'self' is not defined
[2022-06-21 12:22:37,044] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=todoist_load_to_pg, task_id=json_to_df, execution_date=20220621T122230, start_date=20220621T122236, end_date=20220621T122237
[2022-06-21 12:22:37,058] {standard_task_runner.py:89} ERROR - Failed to execute job 512 for task json_to_df
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/todoist_load_to_pg.py", line 55, in json_to_df
    postgres_hook = PostgresHook(self.pg_con)
NameError: name 'self' is not defined
[2022-06-21 12:22:37,099] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-21 12:22:37,139] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
